config/routes.rb
Rails.application.routes.draw do

  mount PostsAPI => '/'

  # root "static_pages#home"
  devise_for :users

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# root to: 'posts#index' , as: 'home'
  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :posts do
    resources :comments
  end

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: 'page'
  end

  resources :posts, concerns: :paginatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments  
  validates :title, presence: true,
		length: {minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 
  before_action :configure_permitted_parameters, if: :devise_controller?
 
  protected
 
  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :authenticate_user!

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        redirect_to post_path(@post)
    end
    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
    end
    private def comment_params
        params.require(:comment).permit(:user, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @title = 'About Us';
        @content = 'This is the about page'
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :authenticate_user! , except:[:index, :show]

    def index
        @post = Post.all.page params[:page]
    end
    def show
        @post = Post.find(params[:id])
    end    
    def new
        @post = Post.new
    end
    def create
        #render plain: params[:post].inspect
        @post = Post.new(post_params)

        if(@post.save)
            redirect_to @post
        else
            render 'new'
        end
    end
    def edit
        @post = Post.find(params[:id])
    end
    def update
        @post = Post.find(params[:id])
    
        if(@post.update(post_params))
            redirect_to @post
        else
            render 'edit'
        end
    
    end
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
    
        redirect_to posts_path
    end
    
    private def post_params
        params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<h3>Comment</h3>
<%= @post.comments.each do |comment| %>
    <div class="well">
        <p><strong><%= comment.user %></strong>: <%= comment.body %>
        <%= link_to '[X]', [comment.post, comment],
                method: :delete,
                data: { confirm: 'Are you want to delete this comment ?' } %>
        </p>
    </div>
<% end %>

app/views/comments/_form.html.erb
<h3>Add Comment</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
        <%= f.label :user %><br>
        <%= f.text_field(:user, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.submit({:class => 'btn btn-default'}) %>
    </p>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RthBlog</title>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  </head>

  <body>

  <div class="container-fluid">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">RthBlog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="navbar-nav">
        <a class="nav-link"  href="#"><%= link_to "Home" , home_path %></a>
      </li>
      <li class="navbar-nav">
        <a class="nav-link" href="#"><%= link_to "Create Post" , new_post_path %>
      </li>
    </ul>
    <ul class="navbar-nav">
    <li><%= link_to "Login" , new_user_session_path %></li>
    <span>|</span>
    <li><%= link_to "Logout" , destroy_user_session_path , method: :delete %></li>
    </ul>
    </div>
</nav>

<div class="container">
    <%= yield %>
</div>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class=”alert alert-danger”><%= msg %></div>
		<% end %>
	<% end %>
    <p>
	<%= f.label :title %><br>
	<%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>

	<p>
    <%= f.label :body %><br>
	<%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>

    <p>
	<%= f.submit({:class => 'btn btn-primary'}) %>
    </p>
<% end %>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>
<hr>
<% @post.each do |post| %>
    <div class="well">
        <h3><%= post.title %></h3>
        <p><%= post.body %></p>
        <%= link_to "Read more" , post_path(post), :class => 'btn btn-default' %>
        <hr>
    </div>
<% end %>
<%= paginate @post, theme: 'twitter-bootstrap-3' %>

app/views/posts/new.html.erb
<h1>Add Post</h1>
<%= form_for :post, url: posts_path do |f| %>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	<p>
	<%= f.label :title %><br>
	<%= f.text_field(:title, {:class => 'form-control'}) %>    </p>
    <p>
    <%= f.label :body %><br>
	<%= f.text_area(:body, {:class => 'form-control'}) %>	</p>
    <p>
	<%= f.submit({:class => 'btn btn-primary'}) %>	</p>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<hr>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-default' %>
<%= link_to "Delete", post_path(@post), 
                method: :delete,
                data: {confirm: 'Are you want to delete this post ?'},
                :class => 'btn btn-danger' %>

<hr>

<%= render 'comments/comments' %>
<%= render 'comments/form' %>